#!/bin/sh

## hyphop ##

# dump android image from eMMC by oowow api

host=${host-vimu}

# get offset for last userdata partition
for OFF in $(ssh root@$host sfdisk --dump /dev/mmcblk0 | grep userdata | grep -m1 -o \ [[:digit:]]*); do
    break
done

BYTES=$((OFF*512))

echo READ $OFF blocks = $BYTES  bytes from ...

curl -L $host/api/disk/rdz/mmc.zst:$BYTES -OJ


<<EOF

## help

zstd -d Edge2.1656697782.4255121408-bytes.emmc.img.zst

# zero userdata

dd if=/dev/zero bs=1M count=4 >> Edge2.1656697782.4255121408-bytes.emmc.img

# pack

./android_pack Edge2.1656697782.4255121408-bytes.emmc.img
